### PR TITLE
Updated Readme.md and contribute.md

### PR DESCRIPTION
**Pull request by sheharyarIshfaq**

### CODE REVIEW

**Comment by shivansh361** [comment]
Great @sheharyarIshfaq

**Comment by sheharyarIshfaq** [comment]
Ok

**Comment by sheharyarIshfaq** [comment]
@shiv0403 I have added the instructions for forking the repo in contributing.md. Should I add a line to star the repository

**Comment by shivansh361** [comment]
yes do it

**Comment by sheharyarIshfaq** [comment]
ok

**Comment by shivansh361** [comment]
Or leave it. its fine now

**Comment by sheharyarIshfaq** [comment]
I have edited. It will be better to show how to fork in the readme

**Pull request merged**
